using './infrastructure.bicep'

param location = 'eastus'
param projectPrefix = 'adimpact'
param environment = 'prod'
param eventHubNamespace = 'adimpact-dev-eh-ns'
param eventHubName = 'ad-impressions'
param functionAppName = 'adimpact-dev-func'
param keyVaultName = 'adimpactdevkv'
param storageAccountName = 'adimpactdevst'
